backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to masterc_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: projects
    file: "static/projects.json"
    fields:
      - label: Title
        name: title
      - label: Projects
        name: projects
        widget: list
        fields:
          - label: Title
            name: title
          - label: Description
            name: description
            widget: markdown
          - label: Image
            name: image
            widget: image                                                                                                          - {label: Photo, name: photo, widget: image}

